### ISSUE TITLE
Pull user's Spotify premium data from Spotify

### ISSUE THREAD

**Issue by peterckim** [nyu-software-engineering/mood-music-player#29]
- [x] Allow user to log into their Spotify Premium account
- [x] Get user's data from Spotify API

Methods to implement in browseController:
- [x] [Get a User's Saved Tracks](https://beta.developer.spotify.com/documentation/web-api/reference/library/get-users-saved-tracks/)
- [x] [Get Audio Features for a Track](https://beta.developer.spotify.com/documentation/web-api/reference/tracks/get-audio-features/)
- [x] [Get Current User's Profile](https://beta.developer.spotify.com/documentation/web-api/reference/users-profile/get-current-users-profile/) (will use this for /account)
- [x] [Get Current User's Saved Albums](https://beta.developer.spotify.com/documentation/web-api/reference/library/get-users-saved-albums/)

**Comment by olinastath** [comment]
@andreawaxman [web api](https://beta.developer.spotify.com/documentation/web-api/)

**Comment by olinastath** [comment]
added methods to implement + links to the corresponding articles on the api's guide
